services:
  postgres:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: M@nagerTi#!
      POSTGRES_DB: db_gerenciador_tarefas